name: rubik_cube_solver
description: Rubik's Cube solver with manual input, patterns & API backend.
publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # HTTP for backend API
  http: ^1.1.0

  # Firebase
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0

  # Nice fonts
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/rotating_cube.gif
